const BOARD_TYPES = {
  BOARD_SUBMIT: 'BOARD_SUBMIT',
  BOARD_SUCCESS: 'BOARD_SUCCESS',
  BOARD_FAILURE: 'BOARD_FAILURE',

  BOARD_GET_ALL_PAGINATION: 'BOARD_GET_ALL_PAGINATION',
  BOARD_GET_ALL: 'BOARD_GET_ALL',
  BOARD_GET_ID: 'BOARD_GET_ID',

};

export default BOARD_TYPES
