const REDIRECT_TYPES = {
  REDIRECT_PAGE_CREATE: 'REDIRECT_PAGE_CREATE',
  REDIRECT_PAGE_CONFIRM: 'REDIRECT_PAGE_CONFIRM',

  REDIRECT_BACK_CREATE: 'REDIRECT_BACK_CREATE',
  REDIRECT_BACK_LIST: 'REDIRECT_BACK_LIST'
};

export default REDIRECT_TYPES
